# Generated by Django 4.2.20 on 2025-04-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
    ]
